default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-mister-cocktail-final_development

test:
  <<: *default
  database: rails-mister-cocktail_test
